[config]
schemaVersion = "0.1.0"


[package]
namespace = "Gunjou"
name = "Hades_II_Approval_Process"
versionNumber = "0.1.0"
description = "Ports over the Pact setting 'Approval Process' from the original Hades as 'Vow of Acceptance'."
websiteUrl = "https://github.com/rajshankarm1213/Hades_II_Approval_Process"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.30"
SGG_Modding-ENVY = "1.0.1"
SGG_Modding-Chalk = "2.0.2"
SGG_Modding-ReLoad = "1.0.1"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "3.1.1"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
